name: "Test server"
description: "Test the currently running medusa server to see if a user has been created and that the server is seeded"

inputs:
  email:
    description: "email of user to log in"
    required: false
    default: "test@test.com"
  password:
    description: "password of user to log in"
    required: false
    default: "password"
  pathToSeedData:
    description: "path to seed data"
    required: false
    default: "cli-test/data/seed.json"
  workingDirectory:
    description: "working directory"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: ls
      shell: "bash"
      run: ls ./node_modules/@medusajs
      working-directory: ${{ inputs.workingDirectory }}

    - name: ls
      shell: "bash"
      run: ls ./node_modules/@medusajs/medusa-cli
      working-directory: ${{ inputs.workingDirectory }}

    - name: Wait for live server response
      shell: "bash"
      working-directory: ${{ inputs.workingDirectory }}
      run: ./node_modules/@medusajs/medusa-cli/scripts/__tests__/wait-for-server-live.sh

    - name: Log in with user
      shell: "bash"
      working-directory: ${{ inputs.workingDirectory }}
      run: ./node_modules/@medusajs/medusa-cli/scripts/__tests__/login.sh ${{ inputs.email }} ${{ inputs.password }}
      #'curl -X POST http://localhost:9000/admin/auth -H "Content-Type: application/json" -d ''{"email":"test@test.com", "password":"password"}'''

    - name: GetProducts
      shell: "bash"
      working-directory: ${{ inputs.workingDirectory }}
      run: ./node_modules/@medusajs/medusa-cli/scripts/__tests__/get-products.sh ${{ inputs.pathToSeedData }}
      # "curl -X GET http://localhost:9000/store/products"

    - name: Kill server
      shell: "bash"
      run: kill -9 $(lsof -t -i :9000)
